# MIT License
#
# Copyright (c) 2025 Quandela
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

from typing import Any

from qat.core.qpu import RemoteQPU

from perceval import ISession, RemoteProcessor
from perceval.runtime.remote_processor import PERFS_KEY
from perceval.utils.logging import channel, get_logger

from .myqlm_helper import MyQLMHelper
from .qpu_handler import QuandelaQPUHandler


class RPCHandler:

    def __init__(self, remote_qpu: RemoteQPU | QuandelaQPUHandler):
        self.remote_qpu = remote_qpu
        self.name = "qpu:myqlm"  # Needed to make the Sampler happy
        self.proxies = None
        self._job_id = 0
        self._job_results: dict[str, Any] = {}

    def fetch_platform_details(self):
        """fetch platform details and settings"""
        hardware_specs = self.remote_qpu.get_specs()

        specs = MyQLMHelper.retrieve_specs(hardware_specs)
        specs[MyQLMHelper.PROGRESS_KEY] = MyQLMHelper.retrieve_progress(hardware_specs)
        specs[MyQLMHelper.WAITING_JOB_KEY] = MyQLMHelper.retrieve_job_in_queue(hardware_specs)

        res = {
            "specs": specs,
            "type": MyQLMHelper.retrieve_type(hardware_specs),
            "status": MyQLMHelper.retrieve_status(hardware_specs),
        }

        try:
            res[PERFS_KEY] = MyQLMHelper.retrieve_perf(hardware_specs)
        except AssertionError:
            pass

        return res

    def create_job(self, payload) -> str:
        """create a job

        :param payload: the payload to send
        :return: job id
        """
        payload["platform_name"] = ""  # Needed to make the QPUHandler happy
        my_qlm_job = MyQLMHelper.make_job_from_payload(payload)
        job_id = str(self._job_id)
        self._job_id += 1
        # TODO: make this async ?
        self._job_results[job_id] = {"results": self.remote_qpu.submit_job(my_qlm_job).meta_data[MyQLMHelper.RESULTS_KEY]}
        return job_id

    def get_job_results(self, job_id: str) -> dict:
        """get job results

        :param job_id: id of the job
        :return: results of the job
        """
        if job_id not in self._job_results:
            raise RuntimeError("The given job id does not exist")
        return self._job_results[job_id]

    def get_job_status(self, job_id: str) -> dict:
        """get the status of a job

        :param job_id: if of the job
        :return: status of the job
        """
        status = "completed" if job_id in self._job_results else "waiting"  # Actually, else not sent, but this status doesn't exist
        return {"status": status}

    def rerun_job(self, job_id: str) -> str:
        raise NotImplementedError("rerun_job is not implemented for MyQLM Remote Processors")

    def cancel_job(self, job_id: str) -> None:
        raise NotImplementedError("cancel_job is not implemented for MyQLM Remote Processors")


class MyQLMSession(ISession):
    """
    Automatic translator allowing to use a MyQLM RemoteQPU as if it was a perceval RemoteProcessor.

    There are a few things that a RemoteProcessor generated by this class can't do, such as:

        - Being used in a JobGroup
        - Retrieving a job from its id (so a job is lost forever if python stops)
        - Some advanced job methods (cancel, rerun...)
        - Jobs will always be executed synchronously

    Usage:

        >>> from perceval_interop import MyQLMSession
        >>> from qat.core.qpu import RemoteQPU
        >>> remote_qpu = RemoteQPU(1212, "middleware.host.address")  # Assuming this is a remote QuandelaQPUHandler
        >>> session = MyQLMSession(remote_qpu)
        >>> processor = session.build_remote_processor()
        >>> # You can now proceed with the processor as if it was any perceval RemoteProcessor.

    The import can also be done through perceval's ProviderFactory:

        >>> import perceval_interop  # Needed to add the MyQLM Session to the providers list used by the factory
        >>> from perceval import ProviderFactory
        >>> from qat.core.qpu import RemoteQPU
        >>> remote_qpu = RemoteQPU(1212, "middleware.host.address")  # Assuming this is a remote QuandelaQPUHandler
        >>> session = ProviderFactory.get_provider("MyQLM", remote_qpu=remote_qpu)
    """

    def __init__(self, remote_qpu: RemoteQPU | QuandelaQPUHandler):
        self.remote_qpu = remote_qpu
        get_logger().info(f"Creating MyQLM Session to {self.remote_qpu}", channel.general)

    def build_remote_processor(self):
        return RemoteProcessor(rpc_handler=RPCHandler(self.remote_qpu))


from perceval import PROVIDER_LIST
PROVIDER_LIST["MyQLM"] = MyQLMSession  # So we can create it from the factory. Interop needs to be imported for this to work
